version: "3.3"
services:
  frontend:
    restart: always
    container_name: frontend
    image: "frontend"
    build:
      context: ./
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5000
      - HOST=0.0.0.0
  backend:
    restart: always
    container_name: backend
    image: "backend"
    build:
      context: ./
      dockerfile: ./backend/docker/Dockerfile
    environment:
      - MESSAGES_AMOUNT=${MESSAGES_AMOUNT}
